### ISSUE TITLE
RPI4 Installation Problem

### ISSUE THREAD

**Issue by WirthmU** [dwkim78/ASTRiDE#12]
When I try to do the python3 test I get:

`
>>> from astride import test
>>> test()
2020-05-24 21:31:43,155 INFO - Start.
2020-05-24 21:31:43,155 INFO - Read a fits file..
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/ASTRiDE/astride/test/run.py", line 17, in test
    area_cut=100)
  File "/home/pi/ASTRiDE/astride/detect.py", line 56, in __init__
    hdulist = fits.open(filename)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 165, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 405, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1054, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/file.py", line 193, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/file.py", line 574, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/pi/.local/lib/python3.7/site-packages/astropy/io/fits/util.py", line 396, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kim/Temp/hst_13003_54_wfc3_ir_f110w_drz_saved.fits'

Any help to this?

**Comment by dwkim78** [comment]
Thanks for reporting the bug. It is fixed in the latest version of ASTRiDE.

**Comment by WirthmU** [comment]
That fixed it.

Thank you
